export const testFileList = [
  ["Skip", "RAR_SITE.TXT", ""],
  ["Skip", "RCVT.TXT", ""],
  ["Skip", "REGISTER.TXT", ""],
  ["Skip", "SFX.TXT", ""],
  ["Tested", "RAR.EXE", "Ok"],
  ["Tested", "RCVT.EXE", "Ok"],
  ["Tested", "UNRAR.EXE", "Ok"],
  ["Tested", "RCVT.CFG", "Error"],
  ["Tested", "REGISTER.FRM", "Ok"],
  ["Tested", "STANDARD.S", "Ok"],
  ["Tested", "IDOS.SFX", "Ok"],
  ["Tested", "OS2.SFX", "Ok"],
  ["Tested", "OS2.RAR", "Ok"],
  ["Tested", "LICENSE.TXT", "Ok"],
  ["Tested", "RAR_SITE.TXT", "Ok"],
  ["Skip", "123VIEW.EXE", ""],
  ["Skip", "PARAVIEW.EXE", ""],
  ["Skip", "ARCVIEW.EXE", ""],
  ["Tested", "WPVIEW.EXE", "Ok"],
  ["Tested", "TERMINAL.EXE", "Ok"],
  ["Tested", "DISKMON.EXE", "Ok"],
  ["Tested", "DISKDOCTOR.EXE", "Ok"],
  ["Tested", "DBVIEW.EXE", "Ok"],
  ["Tested", "SCANDISK.EXE", "Ok"],
  ["Tested", "WINRAR32.EXE", "Ok"]
];
